version: "3"
services:
  db:
    container_name: chimera-db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: MyNewTempPass123
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
  app:
    container_name: chimera-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bash -c "bundle exec puma -C config/puma.rb"
    volumes:
      - .:/app
    depends_on:
      - db
  web:
    container_name: chimera-web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
    environment:
      NGINX_SERVER_NAME: kobushi.com
volumes:
  mysql_data:
