version: "3"
services:
  db:
    container_name: chimera-db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: chimera_development
  app:
    container_name: chimera-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      RAILS_ENV: 'development'
    volumes:
      - .:/app
      - ./vendor/bundle:/app/vendor/bundle:delegated
      - ./node_modules:/app/node_modules:delegated
    ports:
      - 3000:3000
    depends_on:
      - db
    command: >
      bash -c "
        bundle config set path vendor/bundle
        bundle install
        bundle exec puma -C config/puma.rb"
    tty: true
  web:
    container_name: chimera-web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  mysql_data:
