version: "3"
services:
  db:
    container_name: chimera-db
    build:
      context: ./db
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: chimera_development
  frontend:
    container_name: chimera-frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/frontend
      - ./frontend/node_modules:/app/node_modules:delegated
    ports:
      - 8080:8080
    command: >
      bash -c "
        yarn install
        yarn start"
    env_file: .env
  api:
    container_name: chimera-api
    build:
      context: ./api
    environment:
      RAILS_ENV: 'development'
    volumes:
      - ./api:/app/api
      - ./api/vendor/bundle:/app/api/vendor/bundle:delegated
    ports:
      - 3000:3000
    depends_on:
      - db
      - frontend
    command: >
      bash -c "
        bundle config set path vendor/bundle
        bundle install
        bundle exec puma -C config/puma.rb"
    env_file: .env
  web:
    container_name: chimera-web
    build:
      context: ./web
    ports:
      - 80:80
    depends_on:
      - api
volumes:
  mysql_data:
